version: "2.1"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker-intro
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@test.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    depends_on:
      - postgres

  postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgres://postgres:root@postgres:5432/docker-intro
      PGRST_DB_SCHEME: public
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - postgres


